Numpy

Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.


In [1]:
%pip install numpy


   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.3 MB 12.5 MB/s eta 0:00:01
   --------------- ------------------------ 4.7/12.3 MB 17.8 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.3 MB 15.1 MB/s eta 0:00:01
   -------------------------------- ------- 10.0/12.3 MB 14.4 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 13.5 MB/s  0:00:01
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
# create array using numpy
# create a 1D array
arr1 = np.array([1, 2, 3, 4,])
print("1D Array:", arr1)
print("Type:", type(arr1))
print("Shape:", arr1.shape)

1D Array: [1 2 3 4]
Type: <class 'numpy.ndarray'>
Shape: (4,)


In [4]:
# create a 2D array
arr2 = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])
print("2D Array:", arr2)
print("Type:", type(arr2))
print("Shape:", arr2.shape)

2D Array: [[1 2 3 4]
 [4 5 6 7]]
Type: <class 'numpy.ndarray'>
Shape: (2, 4)


In [5]:
np.arange(0, 10, 2).reshape(5, 1) # arrange (start, end, step)
# create a 2D array with 5 rows and 1 column

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [6]:
np.ones((3,4))  # create an array of ones with 3 rows and 4 columns     

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.eye(4)  # create a 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Attributes of numpy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Data type:", arr.dtype)  
print("Size (number of elements):", arr.size)
print("Item size (in bytes):", arr.itemsize)
print("Total size (in bytes):", arr.nbytes)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Number of dimensions: 2
Data type: int64
Size (number of elements): 9
Item size (in bytes): 8
Total size (in bytes): 72


In [9]:
# Numpy Vectorized Operations
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
# Element-wise addition
print("Addition:", a + b)
# Element-wise subtraction  
print("Subtraction:", a - b)
# Element-wise multiplication
print("Multiplication:", a * b)
# Element-wise division
print("Division:", a / b)
# Element-wise square
print("Square of a:", a ** 2)
# Element-wise square root
print("Square root of b:", np.sqrt(b))
# Dot product
print("Dot product:", np.dot(a, b))
# Statistical operations
print("Mean of a:", np.mean(a))

Addition: [11 22 33 44]
Subtraction: [ -9 -18 -27 -36]
Multiplication: [ 10  40  90 160]
Division: [0.1 0.1 0.1 0.1]
Square of a: [ 1  4  9 16]
Square root of b: [3.16227766 4.47213595 5.47722558 6.32455532]
Dot product: 300
Mean of a: 2.5


In [2]:
import numpy as np
# Statistical concepts Normalization and Standardization
data = np.array([10, 20, 30, 40, 50])   
# calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)
# Normalization
normalized_data = (data - mean) / std_dev
print("Normalized Data:", normalized_data)# Standardization

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [4]:
data = np.array([10, 20, 30, 40, 50])
# Mean
mean = np.mean(data)
print("Mean:", mean)
# Median
median = np.median(data)
print("Median:", median)
# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)
# Variance
variance = np.var(data)
print("Variance:", variance)
# Percentiles
percentile_25 = np.percentile(data, 25)
print("25th Percentile:", percentile_25)

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Variance: 200.0
25th Percentile: 20.0


In [6]:
# Logical Operations with Numpy Arrays
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a[a>3] # Elements greater than 3

array([ 4,  5,  6,  7,  8,  9, 10])

In [7]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a[(a>=3) & (a<=7)] # Elements greater than or equal to 3 and less than or equal to 7

array([3, 4, 5, 6, 7])